# Generated by Django 3.2.13 on 2022-06-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('nam', models.CharField(max_length=250)),
                ('des', models.TextField()),
            ],
        ),
    ]
